/**
 * Online Test Service
 * Handles all API calls for online test management:
 * - Generate tests from documents
 * - CRUD operations for tests
 * - Test taking and submission
 * - Progress tracking and results
 */

import { logger } from '@/lib/logger';

// Base API URL - adjust based on environment
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://ai.wordai.pro';

// ==================== Type Definitions ====================

/**
 * Test Attachment (PDF documents)
 * November 14, 2025 - Support for attaching PDF files to tests (reading comprehension, case studies, etc.)
 * Storage: File size tính vào quota của test owner (Free: 50MB, Premium: 2GB, Pro: 15GB, VIP: 50GB)
 */
export interface TestAttachment {
    attachment_id: string; // 12 chars, auto-generated by backend
    title: string; // Required, 1-200 chars
    description?: string; // Optional, max 500 chars
    file_url: string; // Required, max 1000 chars (R2 public URL)
    file_size_mb?: number; // File size in MB, tracked for storage quota
    uploaded_at?: string; // ISO date string, auto-generated
}

export interface AudioSection {
    section_number: number;
    section_title?: string;
    audio_url?: string; // R2 public URL for audio file
    audio_file_id?: string; // File ID in library
    duration_seconds?: number;
    transcript?: string; // Full text transcript
    script?: {
        speaker_roles: string[]; // ["Customer", "Agent"]
        lines: { speaker: number; text: string }[]; // Structured dialogue
    };
    voice_config?: {
        voice_names?: string[]; // ["Aoede", "Charon"]
        num_speakers: number;
    };
    has_audio?: boolean; // Whether audio file exists
    source_type?: 'ai_generated' | 'user_upload'; // Audio source

    // NOTE: Questions are at root level with audio_section field, not nested here
}

// UNIFIED FIELD TYPES (API v2.3 Migration - December 2025)
export type MatchPair = { left_key: string; right_key: string };
export type MapLabelAnswer = { label_key: string; option_key: string };
export type CompletionAnswer = { blank_key: string; answers: string[] }; // [{blank_key: "1", answers: ["text"]}]

export interface TestQuestion {
    question_id: string;
    question_text: string;

    // NEW: 8 Question Types (December 9, 2025 - IELTS support)
    // UPDATED: December 12, 2025 - Added 'mcq_multiple' for multi-answer MCQ questions
    // UPDATED: December 15, 2025 - Added 'true_false_multiple' for Vietnamese exam format
    question_type?: 'mcq' | 'mcq_multiple' | 'essay' | 'matching' | 'map_labeling' | 'completion' | 'sentence_completion' | 'short_answer' | 'true_false_multiple';
    question_number?: number; // Question number in sequence
    max_points?: number; // Points for this question (default: 1 for MCQ, customizable for others)
    instruction?: string; // Instructions specific to this question

    // Grading/feedback fields (owner view only)
    grading_rubric?: string; // Grading guidance for essay questions
    explanation?: string; // Explanation for correct answer (hidden from students)
    sample_answer?: string; // Model answer for essay (hidden from students)

    // MCQ-specific fields (question_type === 'mcq')
    options?: {
        key?: string; // LEGACY: A, B, C, D, E...
        text?: string; // LEGACY
        option_key: string; // NEW: Backend uses this
        option_text: string; // NEW: Backend uses this
    }[];
    correct_answer_key?: string; // LEGACY: Single answer (owner view only)
    correct_answer_keys?: string[]; // LEGACY: Multi-answer support (owner view only)

    // Matching-specific fields (question_type === 'matching')
    left_items?: { key: string; text: string }[]; // Items to match (e.g., [{"key": "1", "text": "John"}])
    right_options?: { key: string; text: string }[]; // Available options (e.g., [{"key": "A", "text": "Paris"}])
    correct_matches?: Record<string, string>; // LEGACY: Owner view only: {"1": "A", "2": "B"}

    // Map Labeling-specific fields (question_type === 'map_labeling')
    diagram_url?: string; // URL to diagram/map image
    diagram_description?: string; // Alt text for diagram
    label_positions?: { key: string; description?: string; x?: number; y?: number }[]; // Label positions
    correct_labels?: Record<string, string>; // LEGACY: Owner view only: {"1": "C", "2": "D"}

    // UNIFIED FIELD (API v2.3 - December 2025)
    // Replaces: correct_answer_keys, correct_matches, correct_labels, and completion correct_answers
    // Type varies by question_type:
    // - MCQ: string[] (e.g., ["A", "B"])
    // - Matching: MatchPair[] (e.g., [{left_key: "1", right_key: "A"}])
    // - Map Labeling: MapLabelAnswer[] (e.g., [{label_key: "1", option_key: "C"}])
    // - Completion: CompletionAnswer[] (e.g., [{blank_key: "1", answers: ["text"]}])
    correct_answers?: string[] | MatchPair[] | MapLabelAnswer[] | CompletionAnswer[];

    // Completion-specific fields (question_type === 'completion')
    template?: string; // Template with blanks: "Flight: [1]_____ Gate: [2]_____"
    blanks?: { key: string; position: string; word_limit?: number }[]; // Blank definitions
    case_sensitive?: boolean; // Default: false

    // Sentence Completion-specific (question_type === 'sentence_completion')
    sentences?: {
        key: string;
        template: string; // "The customer wants to book a flight to _____."
        word_limit?: number;
        correct_answers?: string[]; // Owner view only: ["Paris", "Paris France"]
    }[];

    // Short Answer-specific (question_type === 'short_answer')
    questions?: {
        key: string;
        text: string; // "What is the customer's last name?"
        word_limit?: number;
        correct_answers?: string[]; // Owner view only: ["Smith", "SMITH"]
    }[];

    // True/False Multiple-specific (question_type === 'true_false_multiple')
    // Vietnamese exam format: Multiple true/false statements per question
    statements?: {
        key: string; // "a", "b", "c", "d"
        text: string; // Statement text
        correct_value?: boolean; // Owner view only: true/false
    }[];
    scoring_mode?: 'partial' | 'all_or_nothing'; // Partial: proportional scoring, All-or-nothing: full points or 0
    points?: number; // 1-5 points per question

    // NEW: Listening test fields (December 8, 2025)
    audio_section?: number; // Which audio section this question refers to (1-based)
    timestamp_hint?: string; // Time range hint (e.g., "0:15-0:20")

    // NEW: Media support (November 12, 2025)
    media_type?: 'image' | 'audio';
    media_url?: string; // R2 public URL
    media_description?: string; // Alt text or caption
}

export interface Test {
    test_id: string;
    title: string;
    description?: string | null; // Can be null
    creator_name?: string; // NEW: Optional creator display name (stored at root level)
    document_id?: string;
    creator_id: string;
    created_at: string;
    updated_at: string;
    time_limit_minutes: number;
    max_retries: number;
    passing_score?: number; // Passing score threshold (0-100)
    deadline?: string | null; // Global deadline (ISO 8601)
    show_answers_timing?: 'immediate' | 'after_deadline'; // When to reveal answers
    is_active: boolean;
    language: 'vi' | 'en';
    test_language?: string; // NEW: Language code for translated tests (Dec 3, 2025)
    difficulty?: 'easy' | 'medium' | 'hard';
    total_questions: number;
    num_questions?: number; // Alias for total_questions in V2 API
    questions?: TestQuestion[]; // Only included in specific endpoints
    status?: 'pending' | 'generating' | 'ready' | 'failed' | 'draft' | 'translating';
    progress_percent?: number; // For generating status
    error_message?: string; // For failed status
    job_id?: string; // NEW: Redis worker job ID for tracking (Jan 23, 2026)
    total_submissions?: number; // NEW in V2 - Number of people who took the test
    cover_image?: string; // Cover image URL for public tests
    attachments?: TestAttachment[]; // NEW: PDF attachments (Nov 14, 2025)

    // NEW: Essay support (November 28, 2025)
    test_format?: 'mcq' | 'essay' | 'mixed'; // Test type indicator
    test_type?: 'mcq' | 'essay' | 'mixed' | 'listening'; // NEW: Includes listening tests (Dec 8, 2025)

    // NEW: Listening test support (December 8, 2025)
    num_audio_sections?: number; // Number of audio sections (1-5)
    audio_sections?: AudioSection[]; // Audio files with transcripts

    // Marketplace config (owner view only)
    is_published?: boolean;
    marketplace_config?: {
        is_public?: boolean;
        title?: string;
        description?: string;
        short_description?: string;
        cover_image_url?: string;
        price_points?: number;
        category?: string;
        tags?: string[];
        difficulty_level?: string;
        total_participants?: number;
        total_earnings?: number;
        average_participant_score?: number;
        average_rating?: number;
        rating_count?: number;
        evaluation_criteria?: string; // NEW: AI evaluation criteria (Phase 5)
    };

    // NEW: Diagnostic Test Support (November 29, 2025)
    test_category?: 'academic' | 'diagnostic'; // default: academic
    evaluation_criteria?: string; // JSON string for diagnostic tests (contains result_types and mapping_rules)
    topic?: string; // For general knowledge tests
    source_type?: 'file' | 'document' | 'general_knowledge';
}

export interface PublicTestDetails {
    success: boolean;
    test_id: string;

    // Basic info
    title: string;
    description?: string;
    short_description?: string;
    cover_image_url?: string;

    // Test configuration
    num_questions: number;
    time_limit_minutes: number;
    passing_score: number;
    max_retries: number;

    // Marketplace metadata
    price_points: number;
    category: string;
    tags: string[];
    difficulty_level: string;
    version?: string;
    meta_description?: string; // SEO description (160 chars)
    slug?: string; // SEO-friendly URL slug

    // Community statistics
    total_participants: number;
    average_participant_score: number;
    average_rating: number;
    rating_count: number;

    // Publication info
    published_at?: string;
    creator_id: string;

    // User-specific info
    is_creator: boolean;
    already_participated: boolean;
    attempts_used: number;
    user_best_score?: number;

    // Additional
    creation_type?: string;
    test_language: string;

    // Attachments (November 15, 2025)
    attachments?: TestAttachment[];
}

export interface TestSubmission {
    submission_id: string;
    test_id: string;
    user_id: string;
    attempt_number: number;
    score: number;
    answers: Record<string, string>; // {question_id: answer_key}
    submitted_at: string;
    time_taken_seconds: number;

    // Additional fields returned in submission history (November 29, 2025)
    score_percentage?: number; // 0-100
    total_questions?: number;
    correct_answers?: number;
    is_passed?: boolean;
    grading_status?: 'pending_grading' | 'partially_graded' | 'fully_graded';

    // NEW: Diagnostic Test Support
    test_category?: 'academic' | 'diagnostic';
    is_diagnostic_test?: boolean;
    has_ai_evaluation?: boolean; // false if insufficient points for diagnostic
}

export interface TestSubmissionDetail {
    submission_id: string;
    test_title: string;
    score: number; // Thang điểm 10 (0-10)
    score_percentage: number; // Phần trăm (0-100)
    total_questions: number;
    correct_answers: number;
    time_taken_seconds?: number; // May be hidden
    attempt_number?: number; // May be hidden

    // NEW: Diagnostic Test Support
    test_category?: 'academic' | 'diagnostic';
    is_diagnostic_test?: boolean;
    has_ai_evaluation?: boolean;
    is_passed: boolean; // Pass threshold: >= 5/10
    submitted_at: string;

    // NEW: Test visibility (to determine if AI evaluation is available)
    is_public?: boolean; // True for community tests, false/undefined for private tests

    // NEW: Essay grading support (November 28, 2025)
    grading_status?: 'pending_grading' | 'partially_graded' | 'fully_graded' | 'auto_graded'; // For essay/mixed tests or auto-graded tests
    mcq_score?: number; // MCQ score (out of 10)
    mcq_correct_count?: number; // Number of MCQ questions correct
    essay_score?: number; // Essay score (out of 10)
    essay_total_count?: number; // Total essay questions
    essay_pending?: boolean; // Essays need grading

    results?: {
        question_id: string;
        question_text: string;
        question_type?: 'mcq' | 'mcq_multiple' | 'essay' | 'matching' | 'map_labeling' | 'completion' | 'sentence_completion' | 'short_answer' | 'true_false_multiple'; // NEW: 8 question types (Dec 12: Added mcq_multiple, Dec 15: Added true_false_multiple)

        // Shared fields (all types)
        your_answer?: string; // LEGACY: For MCQ (single key) or Essay text
        max_points?: number; // Maximum points for this question
        points_earned?: number; // Points received (renamed from points_awarded for API consistency)
        points_awarded?: number; // LEGACY: Keep for backward compatibility
        correct?: boolean; // Whether answer is correct
        is_correct?: boolean; // LEGACY: Alias for correct
        feedback?: string; // Grading feedback or scoring explanation
        graded_at?: string; // When graded (essay only)
        explanation?: string; // Explanation for correct answer

        // MCQ-specific fields
        options?: {
            option_key: string;
            option_text: string;
        }[];
        selected_answer_keys?: string[]; // User's selected answers (multi-answer support)
        correct_answer?: string; // LEGACY: Single correct answer
        correct_answer_keys?: string[]; // Correct answer(s)

        // Matching-specific fields
        user_matches?: Record<string, string>; // User's matches: {"1": "A", "2": "B"}
        correct_matches?: Record<string, string>; // Correct matches: {"1": "A", "2": "B"}
        left_items?: { key: string; text: string }[];
        right_options?: { key: string; text: string }[];

        // Map Labeling-specific fields
        user_labels?: Record<string, string>; // User's labels: {"1": "C", "2": "D"}
        correct_labels?: Record<string, string>; // Correct labels: {"1": "C", "2": "D"}
        diagram_url?: string;
        label_positions?: { key: string; description?: string }[];

        // Completion/Sentence/Short Answer-specific fields
        instruction?: string; // Instructions for IELTS types (e.g., "Write NO MORE THAN THREE WORDS")
        user_answers?: Record<string, string>; // User's text answers: {"1": "AF123", "2": "B12"}
        correct_answers?: Record<string, string[]>; // Correct answers: {"1": ["AF123", "Flight AF123"], "2": ["B12"]}
        template?: string; // For completion type
        blanks?: { key: string; position: string; word_limit?: number }[]; // For completion
        sentences?: { key: string; template: string; word_limit?: number }[]; // For sentence_completion (without correct_answers)
        questions?: { key: string; text: string; word_limit?: number; correct_answers?: string[] }[]; // For short_answer (IELTS format: multiple sub-questions OR Regular format: single question)

        // Essay-specific fields
        essay_answer?: string; // Essay text (LEGACY, use your_answer instead)
        media_attachments?: {
            media_type: 'image' | 'audio' | 'document';
            media_url: string;
            filename?: string;
            file_size_mb?: number;
            description?: string;
        }[];

        // True/False Multiple-specific fields
        statements?: {
            key: string; // "a", "b", "c", "d"
            text: string;
            correct_value?: boolean; // Only in results (owner already knows)
        }[];
        scoring_mode?: 'partial' | 'all_or_nothing';
        points?: number; // Alias for max_points
        breakdown?: Record<string, {
            user: boolean;
            correct: boolean;
            is_correct: boolean;
        }>;
    }[]; // May be hidden until deadline

    results_hidden_until_deadline?: string; // ISO date when results will be revealed
    message?: string; // Message explaining when results will be shown
}

// Answer object types for TestSession
export type CurrentAnswerValue =
    | string // Legacy format: single answer key
    | {
        question_type: 'mcq' | 'mcq_multiple';
        selected_answer_keys?: string[];
        selected_answer_key?: string; // Legacy single answer
    }
    | {
        question_type: 'essay';
        essay_answer: string;
        media_attachments?: any[];
    }
    | {
        question_type: 'matching';
        matches: Record<string, string>;
    }
    | {
        question_type: 'map_labeling';
        labels: Record<string, string>;
    }
    | {
        question_type: 'completion' | 'sentence_completion' | 'short_answer';
        answers: Record<string, string>;
    }
    | {
        question_type: 'true_false_multiple';
        answers: Record<string, boolean>; // {"a": true, "b": false, "c": true}
    }
    | Record<string, boolean>; // Direct format for true_false_multiple

export interface TestSession {
    session_id: string;
    test_id: string;
    user_id: string;
    started_at: string;
    current_answers: Record<string, CurrentAnswerValue>; // Updated Dec 12, 2025: Support structured answer objects
    time_remaining_seconds: number;
    time_limit_seconds: number;
    attempt_number: number; // Alias for current_attempt (old field name)
    is_completed: boolean;

    // ✅ NEW: Enhanced attempt tracking
    current_attempt?: number;                // Lần thử hiện tại (1, 2, 3...)
    max_attempts?: number | 'unlimited';     // Tổng số lần cho phép hoặc "unlimited"
    attempts_remaining?: number | 'unlimited'; // Còn lại bao nhiêu lần hoặc "unlimited"
    is_creator?: boolean;                    // ✅ NEW: User là creator của test này

    // ✅ NEW: Test data with questions (returned from /start endpoint)
    test?: Test;  // Full test data including questions
}

export interface GenerateTestRequest {
    source_type: 'document' | 'file'; // Required by API
    source_id: string; // document_id or file_id
    title: string;
    time_limit_minutes: number;
    language: string; // Language code (vi, en, zh, ja, ko, es, fr, de, it, pt, ru, ar, hi, th, id, tr, nl, pl, ro, uk, etc.)
    difficulty: 'easy' | 'medium' | 'hard';
    test_category?: 'academic' | 'diagnostic'; // NEW: Test type (default: academic)
    user_query?: string;

    // Test type configuration (Dec 8, 2025)
    test_type?: 'mcq' | 'essay' | 'mixed'; // Test format (default: mcq)

    // MCQ/Essay configuration
    num_questions?: number; // Total questions for mcq/essay (1-100)
    num_mcq_questions?: number; // MCQ count for mixed (1-100)
    num_essay_questions?: number; // Essay count for mixed (1-20)
    mcq_points?: number; // Total points for MCQ section (mixed only)
    essay_points?: number; // Total points for essay section (mixed only)

    // Multi-answer MCQ configuration
    num_options?: number; // Options per MCQ (2-10, default: 4)
    num_correct_answers?: number; // Correct answers per MCQ (1-10, default: 1)

    // MCQ Type Distribution (Dec 11, 2025)
    mcq_type_config?: {
        distribution_mode?: 'none' | 'auto' | 'manual'; // none = traditional, auto = AI select, manual = user control
        num_single_answer_mcq?: number; // 0-100
        num_multiple_answer_mcq?: number; // 0-100
        num_matching?: number; // 0-100
        num_completion?: number; // 0-100
        num_sentence_completion?: number; // 0-100
        num_short_answer?: number; // 0-100
    };
}

export interface GenerateTestFromAIRequest {
    title: string; // 5-200 chars
    description?: string; // max 1000 chars
    topic: string; // 3-200 chars, e.g. 'Leadership Styles', 'Python Programming'
    user_query: string; // 10-2000 chars, detailed instructions
    test_category?: 'academic' | 'diagnostic'; // default: academic
    language: string; // Language code (vi, en, zh, ja, ko, es, fr, de, it, pt, ru, ar, hi, th, id, tr, nl, pl, ro, uk, etc.)
    difficulty?: 'easy' | 'medium' | 'hard';
    time_limit_minutes: number; // 1-270, default: 30
    max_retries: number; // 1-10, default: 3
    passing_score: number; // 0-100, default: 70
    deadline?: string; // ISO datetime
    show_answers_timing?: 'immediate' | 'after_deadline'; // default: immediate
    creator_name?: string; // Optional creator display name (2-100 chars)

    // Test type configuration (Dec 8, 2025)
    test_type?: 'mcq' | 'essay' | 'mixed'; // Test format (default: mcq)

    // MCQ/Essay configuration
    num_questions?: number; // Total questions for mcq/essay (1-100)
    num_mcq_questions?: number; // MCQ count for mixed (1-100)
    num_essay_questions?: number; // Essay count for mixed (1-20)
    mcq_points?: number; // Total points for MCQ section (mixed only)
    essay_points?: number; // Total points for essay section (mixed only)

    // Multi-answer MCQ configuration
    num_options?: number; // Options per MCQ (2-10, default: 4)
    num_correct_answers?: number; // Correct answers per MCQ (1-10, default: 1)

    // MCQ Type Distribution (Dec 11, 2025)
    mcq_type_config?: {
        distribution_mode?: 'none' | 'auto' | 'manual'; // none = traditional, auto = AI select, manual = user control
        num_single_answer_mcq?: number; // 0-100
        num_multiple_answer_mcq?: number; // 0-100
        num_matching?: number; // 0-100
        num_completion?: number; // 0-100
        num_sentence_completion?: number; // 0-100
        num_short_answer?: number; // 0-100
    };
}

/**
 * Generate Listening Test Request (Dec 8, 2025)
 * POST /api/v1/tests/generate/listening
 */
export interface GenerateListeningTestRequest {
    title: string; // 5-200 chars
    description?: string; // max 1000 chars
    language: string; // en, zh, fr, vi, etc.
    topic?: string; // 3-200 chars (optional when using transcript/audio)
    difficulty?: 'easy' | 'medium' | 'hard'; // default: medium
    num_questions: number; // 1-50
    num_audio_sections: number; // 1-5

    // Phase 7 & 8: Alternative audio sources (Dec 9, 2025)
    user_transcript?: string; // 50-5000 chars (Phase 7: User-provided transcript)
    audio_file_path?: string; // Audio file temp path (Phase 8: Uploaded audio file)

    audio_config: {
        num_speakers: 1 | 2; // monologue or dialogue
        speaker_genders?: string[]; // e.g. ["female", "male"]
        voice_names?: string[]; // e.g. ["Aoede", "Charon"]
        speaking_rate?: number; // 0.5-2.0, default: 1.0
    };
    user_query: string; // 10-2000 chars, instructions for AI
    time_limit_minutes?: number; // 1-270, default: 30
    passing_score?: number; // 0-100, default: 70
    use_pro_model?: boolean; // Use pro TTS model, default: false
}

export interface TestAttemptInfo {
    test_id: string;
    test_title: string;
    max_retries: number | 'unlimited';  // ✅ Support "unlimited" for creators
    attempts_used: number;
    attempts_remaining: number | 'unlimited';  // ✅ Support "unlimited" for creators
    best_score: number | null;
    can_retake: boolean;
    is_creator?: boolean; // ✅ NEW: Is user the creator
    submissions: {
        submission_id: string;
        attempt_number: number;
        score: number;
        score_percentage: number; // ✅ NEW: Percentage (0-100)
        correct_answers: number;  // ✅ NEW: Number of correct answers
        total_questions: number;  // ✅ NEW: Total questions
        is_passed: boolean;       // ✅ NEW: Pass/Fail status
        time_taken_seconds: number; // ✅ NEW: Time taken
        passed: boolean;          // Legacy field (same as is_passed)
        submitted_at: string;
    }[];
}

// ==================== Participants (Owner Only) ====================

export interface TestParticipant {
    user_id: string;
    email: string;
    display_name: string;
    photo_url?: string;
    num_attempts: number;           // Tổng số lần thử
    best_score: number;             // Điểm cao nhất (thang 10)
    total_correct_answers: number;  // Tổng câu đúng (all attempts)
    avg_time_seconds: number;       // Thời gian trung bình
    latest_submission_at: string;   // Lần nộp bài mới nhất
    has_submitted: boolean;
}

export interface GetTestParticipantsResponse {
    test_id: string;
    test_title: string;
    total_participants: number;
    participants: TestParticipant[];
    pagination: {
        page: number;
        page_size: number;
        total_items: number;
        total_pages: number;
        has_next: boolean;
        has_prev: boolean;
    };
}

// ==================== Ratings (Public Test Reviews) ====================

export interface TestRating {
    rating_id: string;
    rating: number;              // 1-5 stars
    comment: string;             // Optional comment
    created_at: string;
    updated_at: string;
    user: {
        uid: string;
        display_name: string;
        photo_url?: string | null;
    };
}

export interface GetTestRatingsResponse {
    success: boolean;
    data: {
        ratings: TestRating[];
        summary: {
            avg_rating: number;
            total_ratings: number;
        };
        pagination: {
            page: number;
            page_size: number;
            total_items: number;
            total_pages: number;
            has_next: boolean;
            has_prev: boolean;
        };
    };
}

export interface SubmitRatingRequest {
    rating: number;              // 1-5 stars (required)
    comment?: string;            // Optional comment
}

export interface SubmitRatingResponse {
    success: boolean;
    message: string;
    rating_id?: string;
}

export interface GetMyTestsResponse {
    tests: Test[];
    total: number;
    limit: number;
    offset: number;
    has_more: boolean;
}

// NEW: Grouped submissions by test (November 29, 2025)
export interface TestSubmissionGroup {
    test_id: string;
    test_title: string;
    test_category?: 'academic' | 'diagnostic'; // NEW: Test type
    is_owner: boolean;
    total_attempts: number;
    best_score: number | null;
    latest_attempt_at: string;
    submission_history: TestSubmission[];
}

export interface GetMySubmissionsGroupedResponse {
    success: boolean;
    tests: TestSubmissionGroup[];
    total_tests: number;
}

// ==================== Answer Media Attachments (Essay Support) ====================

export interface AnswerMediaAttachment {
    media_type: 'image' | 'audio' | 'document';
    media_url: string;
    filename: string;
    file_size_mb: number;
    description?: string;
}

export interface PresignedUrlResponse {
    success: boolean;
    presigned_url: string;
    file_url: string;
    file_size_mb: number;
    expires_in: number;
}

// ==================== Essay Grading Interfaces ====================
// November 28, 2025 - Essay grading system (Phases 4-5)

export interface GradingQueueItem {
    submission_id: string;
    student_id: string;
    student_name: string | null;
    submitted_at: string; // ISO 8601
    essay_question_count: number;
    graded_count: number;
    assigned_to: string | null;
    priority: number;
    status: 'pending' | 'in_progress' | 'completed';
}

export interface GetGradingQueueResponse {
    success: boolean;
    test_id: string;
    test_title: string;
    total_count: number;
    queue: GradingQueueItem[];
}

export interface EssayQuestion {
    question_id: string;
    question_text: string;
    max_points: number;
    grading_rubric: string | null;
    student_answer: string;
    current_grade: {
        points_awarded: number;
        feedback: string | null;
        graded_by: string;
        graded_at: string;
    } | null;
}

export interface GetGradingViewResponse {
    success: boolean;
    submission_id: string;
    test_id: string;
    test_title: string;
    student_id: string;
    student_name: string;
    student_email: string;
    submitted_at: string;
    time_taken_seconds: number;
    grading_status: 'pending_grading' | 'partially_graded' | 'fully_graded' | 'auto_graded';
    mcq_summary: {
        mcq_score: number | null; // null for pure essay tests
        mcq_correct_count: number;
    };
    essay_questions: EssayQuestion[];
}

// New interface for /grading-details endpoint (includes sample_answer)
export interface EssayQuestionForGrading extends EssayQuestion {
    sample_answer?: string; // Sample/model answer from teacher
    media_attachments?: AnswerMediaAttachment[]; // Student's uploaded files
}

export interface GetGradingDetailsResponse {
    success: boolean;
    submission_id: string;
    test_id: string;
    test_title: string;
    user_id: string;
    user_name: string;
    user_email: string;
    submitted_at: string;
    mcq_score: number | null;
    mcq_correct_count: number;
    essay_graded_count: number;
    essay_question_count: number;
    grading_status: 'auto_graded' | 'pending_grading' | 'partially_graded' | 'completed';
    essay_questions: EssayQuestionForGrading[];
}

// AI Evaluation History interfaces
export interface AIEvaluationHistoryItem {
    evaluation_id: string;
    submission_id: string;
    test_id: string;
    test_title: string;
    test_category: string;
    overall_evaluation: {
        overall_rating?: number;
        strengths?: string[];
        weaknesses?: string[];
        recommendations?: string[];
        study_plan?: string;
        result_title?: string;
        result_description?: string;
        personality_traits?: string[];
        advice?: string[];
        iq_score?: number;
        iq_category?: string;
    };
    question_evaluations: Array<{
        question_id: string;
        question_type?: string;
        question_text?: string;
        user_answer: string | Record<string, boolean>;
        correct_answer?: string | Record<string, boolean>;
        is_correct?: boolean;
        ai_feedback: string;
        improvement_tips?: string[];
        explanation?: string;
        options?: Array<{
            option_key: string;
            option_text: string;
        }>;
        statements?: Array<{
            key: string;
            text: string;
            correct_value?: boolean;
        }>;
        max_points?: number;
    }>;
    model: string;
    generation_time_ms: number;
    points_cost: number;
    language: string;
    created_at: string;
}

export interface GetSubmissionEvaluationsResponse {
    success: boolean;
    evaluations: AIEvaluationHistoryItem[];
    total: number;
    page: number;
    limit: number;
}

export interface GradeEssayRequest {
    question_id: string;
    points_awarded: number;
    feedback?: string;
}

export interface GradeEssayResponse {
    success: boolean;
    submission_id: string;
    question_id: string;
    points_awarded: number;
    max_points: number;
    grading_status: string;
    graded_essays: number;
    total_essays: number;
    final_score: {
        score: number;
        score_percentage: number;
        is_passed: boolean;
        total_score: number;
        max_total: number;
    } | null;
}

export interface GradeAllEssaysRequest {
    grades: {
        question_id: string;
        points_awarded: number;
        feedback?: string;
    }[];
}

export interface GradeAllEssaysResponse {
    success: boolean;
    submission_id: string;
    grading_status: string;
    graded_essays: number;
    final_score: {
        score: number;
        score_percentage: number;
        is_passed: boolean;
        total_score: number;
        max_total: number;
    };
}

export interface GetGradingDashboardResponse {
    success: boolean;
    total_pending: number;
    tests_with_pending: {
        test_id: string;
        test_title: string;
        pending_count: number;
        oldest_submission: string;
    }[];
    recently_graded: {
        submission_id: string;
        test_title: string;
        student_name: string;
        submitted_at: string;
        graded_count: number;
        essay_question_count: number;
    }[];
}

// ==================== Helper Functions ====================

/**
 * Get authorization headers with JWT token
 */
async function getAuthHeaders(): Promise<HeadersInit> {
    const headers: HeadersInit = {
        'Content-Type': 'application/json',
    };

    // Get fresh Firebase ID token using token manager (same as other services)
    try {
        const { firebaseTokenManager } = await import('./firebaseTokenManager');

        // Retry logic: Try up to 3 times with delay if token is null (Firebase might be initializing)
        let token: string | null = null;
        let attempts = 0;
        const maxAttempts = 3;

        while (!token && attempts < maxAttempts) {
            token = await firebaseTokenManager.getValidToken();

            if (!token && attempts < maxAttempts - 1) {
                // Wait 500ms before retry
                await new Promise(resolve => setTimeout(resolve, 500));
                logger.info(`🔄 Retrying token fetch (attempt ${attempts + 2}/${maxAttempts})`);
            }
            attempts++;
        }

        if (token) {
            headers['Authorization'] = `Bearer ${token}`;
            logger.dev('🔑 Auth token added to headers');
        } else {
            logger.warn('⚠️ No auth token available from firebaseTokenManager after retries');
        }
    } catch (error) {
        logger.error('❌ Error getting auth token:', error);
    }

    return headers;
}

/**
 * Get optional authorization headers (for public endpoints that work with or without auth)
 */
async function getOptionalAuthHeaders(): Promise<HeadersInit> {
    const headers: HeadersInit = {
        'Content-Type': 'application/json',
    };

    // Try to get token, but don't fail if not available
    try {
        const { firebaseTokenManager } = await import('./firebaseTokenManager');
        const token = await firebaseTokenManager.getValidToken();

        if (token) {
            headers['Authorization'] = `Bearer ${token}`;
            logger.dev('🔑 Optional auth token added to headers');
        } else {
            logger.info('ℹ️ No auth token available, proceeding without authentication');
        }
    } catch (error) {
        logger.info('ℹ️ Auth token not available, proceeding without authentication');
    }

    return headers;
}

/**
 * Handle API response errors
 */
async function handleResponse<T>(response: Response): Promise<T> {
    if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMessage = errorData.detail || errorData.message || `HTTP ${response.status}: ${response.statusText}`;

        logger.error('❌ API Error:', {
            status: response.status,
            statusText: response.statusText,
            error: errorData
        });

        throw new Error(errorMessage);
    }

    return response.json();
}

// ==================== Test Generation ====================

/**
 * Generate a new test from document using AI
 */
export async function generateTestFromDocument(
    request: GenerateTestRequest,
    signal?: AbortSignal // Optional abort signal for timeout
): Promise<Test> {
    try {
        logger.info('🤖 Generating test from document:', request);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/generate`, {
            method: 'POST',
            headers,
            body: JSON.stringify(request),
            signal, // Pass abort signal
        });

        const result = await handleResponse<Test>(response);
        logger.info('✅ Test generated successfully:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to generate test:', error);
        throw error;
    }
}

/**
 * Generate a new test from AI general knowledge (no file source)
 */
export async function generateTestFromAI(
    request: GenerateTestFromAIRequest,
    signal?: AbortSignal // Optional abort signal for timeout
): Promise<Test> {
    try {
        logger.info('🤖 Generating test from AI knowledge:', request);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/generate/general`, {
            method: 'POST',
            headers,
            body: JSON.stringify(request),
            signal, // Pass abort signal
        });

        const result = await handleResponse<Test>(response);
        logger.info('✅ Test generated successfully:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to generate test from AI:', error);
        throw error;
    }
}

/**
 * Generate a new listening test with AI-generated audio (Dec 8, 2025)
 */
export async function generateListeningTest(
    request: GenerateListeningTestRequest,
    signal?: AbortSignal // Optional abort signal for timeout
): Promise<Test> {
    try {
        logger.info('🎧 Generating listening test:', request);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/generate/listening`, {
            method: 'POST',
            headers,
            body: JSON.stringify(request),
            signal, // Pass abort signal
        });

        const result = await handleResponse<Test>(response);
        logger.info('✅ Listening test generated successfully:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to generate listening test:', error);
        throw error;
    }
}

// ==================== Test CRUD Operations ====================

/**
 * Get test by ID (for taking test - no answers included)
 */
export async function getTest(testId: string): Promise<Test> {
    try {
        logger.info('📖 Fetching test:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<Test>(response);

        // DEBUG: RAW API RESPONSE


        // DEBUG: Log evaluation_criteria for diagnostic tests
        if (result.test_category === 'diagnostic') {
            logger.info('🔍 Diagnostic test loaded (getTest):', {
                test_id: testId,
                test_category: result.test_category,
                has_evaluation_criteria: !!result.evaluation_criteria,
                evaluation_criteria_length: result.evaluation_criteria?.length
            });
        }

        //  NORMALIZE: Map option_key/option_text to key/text for frontend compatibility
        if (result.questions) {
            result.questions = result.questions.map(q => {
                const normalized: any = {
                    ...q,
                    options: (q.options || []).map(opt => ({
                        key: opt.option_key || opt.key || '',
                        text: opt.option_text || opt.text || '',
                        option_key: opt.option_key || opt.key || '',
                        option_text: opt.option_text || opt.text || ''
                    })),
                    correct_answer_key: q.correct_answer_key || (q.correct_answer_keys && q.correct_answer_keys[0]) || '',
                    max_points: q.max_points || 1
                };

                // NORMALIZE: Ensure correct_answers field exists (backward compatibility)
                // Backend may send correct_answers OR legacy fields, handle both

                // MCQ: Ensure correct_answers is array
                if (q.question_type === 'mcq' || q.question_type === 'mcq_multiple') {
                    if (!q.correct_answers || !Array.isArray(q.correct_answers) || q.correct_answers.length === 0) {
                        // Fallback to legacy fields
                        if (q.correct_answer_keys && q.correct_answer_keys.length > 0) {
                            normalized.correct_answers = q.correct_answer_keys;
                        } else if (q.correct_answer_key) {
                            normalized.correct_answers = [q.correct_answer_key];
                        }
                    } else {
                        // Backend sent correct_answers, keep it
                        normalized.correct_answers = q.correct_answers;
                    }
                }

                // Matching: Keep correct_answers as array for display, but also create object version
                if (q.question_type === 'matching') {
                    // Convert correct_matches from array to object for backward compatibility
                    if (Array.isArray(q.correct_matches)) {
                        normalized.correct_matches = (() => {
                            const matchesObj: Record<string, string> = {};
                            (q.correct_matches as any[]).forEach((match: any) => {
                                if (match.left_key && match.right_key) {
                                    matchesObj[match.left_key] = match.right_key;
                                }
                            });
                            return matchesObj;
                        })();
                    }
                    // Ensure correct_answers exists (backend should send this)
                    if (q.correct_answers && Array.isArray(q.correct_answers)) {
                        normalized.correct_answers = q.correct_answers;
                    }
                }

                // Map Labeling: Keep correct_answers as array for display
                if (q.question_type === 'map_labeling') {
                    if (q.correct_answers && Array.isArray(q.correct_answers)) {
                        normalized.correct_answers = q.correct_answers;
                    }
                }

                // Completion: Keep correct_answers as array for display
                if (q.question_type === 'completion') {
                    if (q.correct_answers && Array.isArray(q.correct_answers)) {
                        normalized.correct_answers = q.correct_answers;
                    }
                }

                // Sentence Completion & Short Answer: Keep correct_answers as-is
                // These types have correct_answers inside sentences[]/questions[] arrays
                if (q.question_type === 'sentence_completion' || q.question_type === 'short_answer') {
                    // Backend handles these at sub-question level
                    // No normalization needed
                }

                return normalized;
            });

            // INFER test_format if missing (for backward compatibility)
            if (!result.test_format && result.questions.length > 0) {
                const hasEssay = result.questions.some(q => q.question_type === 'essay');
                const hasMcq = result.questions.some(q => q.question_type === 'mcq' || !q.question_type);

                if (hasEssay && hasMcq) {
                    result.test_format = 'mixed';
                } else if (hasEssay) {
                    result.test_format = 'essay';
                } else {
                    result.test_format = 'mcq';
                }
                logger.info('ℹ️ Inferred test format:', result.test_format);
            }
        }

        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch test:', error);
        throw error;
    }
}

/**
 * Get test preview with answers (creator only)
 */
export async function getTestPreview(testId: string): Promise<Test> {
    try {
        logger.info('👁️ Fetching test preview:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/preview`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<Test>(response);

        // DEBUG: Log evaluation_criteria for diagnostic tests
        if (result.test_category === 'diagnostic') {
            logger.info('🔍 Diagnostic test loaded:', {
                test_id: testId,
                test_category: result.test_category,
                has_evaluation_criteria: !!result.evaluation_criteria,
                evaluation_criteria_length: result.evaluation_criteria?.length
            });
        }

        //  NORMALIZE: Map option_key/option_text to key/text for frontend compatibility
        if (result.questions) {
            result.questions = result.questions.map(q => ({
                ...q,
                options: (q.options || []).map(opt => ({
                    key: opt.option_key || opt.key || '',
                    text: opt.option_text || opt.text || '',
                    option_key: opt.option_key || opt.key || '',
                    option_text: opt.option_text || opt.text || ''
                })),
                correct_answer_key: q.correct_answer_key || (q.correct_answer_keys && q.correct_answer_keys[0]) || '',
                // Preserve max_points if exists
                max_points: q.max_points || 1
            }));

            // INFER test_format if missing (for backward compatibility)
            if (!result.test_format && result.questions.length > 0) {
                const hasEssay = result.questions.some(q => q.question_type === 'essay');
                const hasMcq = result.questions.some(q => q.question_type === 'mcq' || q.question_type === 'mcq_multiple' || !q.question_type); // Default to mcq if type missing

                if (hasEssay && hasMcq) {
                    result.test_format = 'mixed';
                } else if (hasEssay) {
                    result.test_format = 'essay';
                } else {
                    result.test_format = 'mcq';
                }
                logger.info('ℹ️ Inferred test format:', result.test_format);
            }
        }

        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch test preview:', error);
        throw error;
    }
}

/**
 * Get public test details from marketplace (full info with stats)
 * Can use either testId or slug
 */
export async function getPublicTestDetails(testId: string): Promise<PublicTestDetails> {
    try {
        logger.info('🌍 Fetching public test details:', testId);

        const headers = await getOptionalAuthHeaders(); // Allow anonymous access
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/marketplace/details`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<PublicTestDetails>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch public test details:', error);
        throw error;
    }
}

/**
 * Get public test details by slug (SEO-friendly)
 */
export async function getPublicTestDetailsBySlug(slug: string): Promise<PublicTestDetails> {
    try {
        logger.info('🌍 Fetching public test details by slug:', slug);

        const headers = await getOptionalAuthHeaders(); // Allow anonymous access
        const response = await fetch(`${API_BASE_URL}/api/v1/marketplace/tests/by-slug/${slug}`, {
            method: 'GET',
            headers,
        });

        // Response structure: { success: boolean, data: PublicTestDetails }
        const json = await handleResponse<{ success: boolean; data: PublicTestDetails }>(response);
        const result = json.data || json; // Handle both wrapped and unwrapped responses

        // Verify critical fields are present
        if (!result.test_id) {
            logger.error('❌ API response missing test_id:', result);
            throw new Error('Invalid API response: missing test_id');
        }

        logger.info('✅ Test details fetched by slug, test_id:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch public test details by slug:', error);
        throw error;
    }
}

/**
 * Update test questions (creator only)
 */
export async function updateTestQuestions(
    testId: string,
    questions: TestQuestion[]
): Promise<{ success: boolean; questions_updated: number }> {
    try {
        logger.info('✏️ Updating test questions:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/questions`, {
            method: 'PUT',
            headers,
            body: JSON.stringify({ questions }),
        });

        const result = await handleResponse<{ success: boolean; questions_updated: number }>(response);
        logger.info('✅ Test questions updated successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to update test questions:', error);
        throw error;
    }
}

/**
 * Update test configuration (creator only)
 */
export async function updateTestConfig(
    testId: string,
    config: {
        title?: string;
        description?: string;
        creator_name?: string; // NEW: Optional creator display name (2-100 chars)
        test_language?: 'vi' | 'en'; // NEW: Test language (Dec 17, 2025)
        time_limit_minutes?: number;
        max_retries?: number;
        deadline?: string;
        show_answers_timing?: 'immediate' | 'after_deadline';
        is_active?: boolean;
        attachments?: Omit<TestAttachment, 'attachment_id' | 'uploaded_at'>[]; // NEW: Optional attachments (replaces all)
    }
): Promise<{ success: boolean; updated_fields: string[] }> {
    try {
        logger.info('⚙️ Updating test config:', testId, config);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/config`, {
            method: 'PATCH',
            headers,
            body: JSON.stringify(config),
        });

        const result = await handleResponse<{ success: boolean; updated_fields: string[] }>(response);
        logger.info('✅ Test config updated successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to update test config:', error);
        throw error;
    }
}

/**
 * Delete test (soft delete - sets is_active = false)
 */
export async function deleteTest(testId: string): Promise<{ success: boolean }> {
    try {
        logger.info('🗑️ Deleting test:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}`, {
            method: 'DELETE',
            headers,
        });

        const result = await handleResponse<{ success: boolean }>(response);
        logger.info('✅ Test deleted successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to delete test:', error);
        throw error;
    }
}

/**
 * Update marketplace configuration for published test
 */
export async function updateMarketplaceConfig(
    testId: string,
    config: {
        category?: string;
        tags?: string[];
        difficulty_level?: string;
        short_description?: string;
        price_points?: number;
    }
): Promise<{ success: boolean; updated_fields: string[] }> {
    try {
        logger.info('🛒 Updating marketplace config:', testId, config);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/marketplace/config`, {
            method: 'PATCH',
            headers,
            body: JSON.stringify(config),
        });

        const result = await handleResponse<{ success: boolean; updated_fields: string[] }>(response);
        logger.info('✅ Marketplace config updated successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to update marketplace config:', error);
        throw error;
    }
}

// ==================== Test Attachments (November 14, 2025) ====================

/**
 * Get presigned URL for uploading PDF to R2 storage
 * Access: Authenticated users
 * Returns presigned URL (valid 5 minutes) and final file URL
 * Storage: File size checked against owner's storage quota
 */
export async function getPresignedUrl(
    filename: string,
    fileSizeMb: number,
    contentType: string = 'application/pdf'
): Promise<{
    success: boolean;
    presigned_url: string;
    file_url: string;
    file_size_mb: number;
    expires_in: number;
}> {
    try {
        logger.info('🔑 Getting presigned URL for:', filename, `(${fileSizeMb.toFixed(2)}MB)`);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/attachments/presigned-url`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                filename,
                file_size_mb: fileSizeMb,
                content_type: contentType,
            }),
        });

        const result = await handleResponse<{
            success: boolean;
            presigned_url: string;
            file_url: string;
            file_size_mb: number;
            expires_in: number;
        }>(response);

        logger.info('✅ Presigned URL received, expires in:', result.expires_in, 'seconds');
        return result;
    } catch (error) {
        logger.error('❌ Failed to get presigned URL:', error);
        throw error;
    }
}

/**
 * Upload file directly to R2 using presigned URL
 * No authentication needed (presigned URL already contains signature)
 */
export async function uploadToR2(
    presignedUrl: string,
    file: File,
    onProgress?: (progress: number) => void
): Promise<void> {
    try {
        logger.info('📤 Uploading file to R2:', file.name, `(${(file.size / 1024 / 1024).toFixed(2)}MB)`);

        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();

            // Track upload progress
            xhr.upload.addEventListener('progress', (e) => {
                if (e.lengthComputable && onProgress) {
                    const progress = Math.round((e.loaded / e.total) * 100);
                    onProgress(progress);
                }
            });

            // Handle completion
            xhr.addEventListener('load', () => {
                if (xhr.status >= 200 && xhr.status < 300) {
                    logger.info('✅ File uploaded to R2 successfully');
                    resolve();
                } else {
                    logger.error('❌ R2 upload failed:', xhr.status, xhr.statusText);
                    reject(new Error(`Upload failed: ${xhr.status} ${xhr.statusText}`));
                }
            });

            // Handle errors
            xhr.addEventListener('error', () => {
                logger.error('❌ Network error during R2 upload');
                reject(new Error('Network error during upload'));
            });

            xhr.addEventListener('abort', () => {
                logger.warn('⚠️ Upload aborted');
                reject(new Error('Upload aborted'));
            });

            // Send PUT request with file
            xhr.open('PUT', presignedUrl);
            xhr.setRequestHeader('Content-Type', file.type);
            xhr.send(file);
        });
    } catch (error) {
        logger.error('❌ Failed to upload to R2:', error);
        throw error;
    }
}

/**
 * Get all attachments for a test
 * Access: Owner gets full list, others get public list
 */
export async function getAttachments(
    testId: string
): Promise<{
    success: boolean;
    test_id: string;
    test_title: string;
    creator_id: string;
    is_owner: boolean;
    attachments: TestAttachment[];
    total_attachments: number;
    total_storage_mb: number;
}> {
    try {
        logger.info('📎 Loading attachments for test:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/attachments`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            test_title: string;
            creator_id: string;
            is_owner: boolean;
            attachments: TestAttachment[];
            total_attachments: number;
            total_storage_mb: number;
        }>(response);

        logger.info('✅ Loaded attachments:', result.attachments.length);
        return result;
    } catch (error) {
        logger.error('❌ Failed to load attachments:', error);
        throw error;
    }
}

/**
 * Add attachment to test (PDF documents)
 * Access: Owner only
 */
export async function addAttachment(
    testId: string,
    attachment: Omit<TestAttachment, 'attachment_id' | 'uploaded_at'>
): Promise<{
    success: boolean;
    test_id: string;
    attachment: TestAttachment;
    message: string;
}> {
    try {
        logger.info('📎 Adding attachment to test:', testId, attachment.title);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/attachments`, {
            method: 'POST',
            headers,
            body: JSON.stringify(attachment),
        });

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            attachment: TestAttachment;
            message: string;
        }>(response);

        logger.info('✅ Attachment added successfully:', result.attachment.attachment_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to add attachment:', error);
        throw error;
    }
}

/**
 * Update attachment
 * Access: Owner only
 */
export async function updateAttachment(
    testId: string,
    attachmentId: string,
    data: Partial<Omit<TestAttachment, 'attachment_id' | 'uploaded_at'>>
): Promise<{
    success: boolean;
    test_id: string;
    attachment_id: string;
    message: string;
}> {
    try {
        logger.info('✏️ Updating attachment:', testId, attachmentId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/attachments/${attachmentId}`, {
            method: 'PUT',
            headers,
            body: JSON.stringify(data),
        });

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            attachment_id: string;
            message: string;
        }>(response);

        logger.info('✅ Attachment updated successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to update attachment:', error);
        throw error;
    }
}

/**
 * Delete attachment
 * Access: Owner only
 */
export async function deleteAttachment(
    testId: string,
    attachmentId: string
): Promise<{
    success: boolean;
    test_id: string;
    attachment_id: string;
    message: string;
}> {
    try {
        logger.info('🗑️ Deleting attachment:', testId, attachmentId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/attachments/${attachmentId}`, {
            method: 'DELETE',
            headers,
        });

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            attachment_id: string;
            message: string;
        }>(response);

        logger.info('✅ Attachment deleted successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to delete attachment:', error);
        throw error;
    }
}

// ==================== Test Taking ====================

/**
 * Start a test session
 */
export async function startTest(testId: string): Promise<TestSession> {
    try {
        logger.info('🚀 Starting test session:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/start`, {
            method: 'POST',
            headers,
        });

        const result = await handleResponse<TestSession>(response);

        logger.info('✅ Test session started:', result.session_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to start test:', error);
        throw error;
    }
}

/**
 * Get presigned URL for uploading answer media attachments (essay questions)
 */
export async function getPresignedUrlForAnswerMedia(
    filename: string,
    fileSizeMb: number,
    contentType: string
): Promise<PresignedUrlResponse> {
    try {
        logger.info('📎 Getting presigned URL for answer media:', filename);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/submissions/answer-media/presigned-url`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                filename,
                file_size_mb: fileSizeMb,
                content_type: contentType
            }),
        });

        const result = await handleResponse<PresignedUrlResponse>(response);
        logger.info('✅ Presigned URL generated:', result.file_url);
        return result;
    } catch (error) {
        logger.error('❌ Failed to get presigned URL:', error);
        throw error;
    }
}

/**
 * Submit test answers
 * Support both MCQ and Essay answers
 */
export async function submitTest(
    testId: string,
    sessionId: string,
    questions: TestQuestion[], // ✅ NEW: All questions to ensure we send all answers
    answers: Record<string, string>,
    essayAnswers?: Record<string, { essay_answer: string; media_attachments?: AnswerMediaAttachment[] }>,
    matchingAnswers?: Record<string, Record<string, string>>,
    mapLabelingAnswers?: Record<string, Record<string, string>>,
    completionAnswers?: Record<string, Record<string, string>>,
    sentenceCompletionAnswers?: Record<string, Record<string, string>>,
    shortAnswerAnswers?: Record<string, Record<string, string>>,
    trueFalseAnswers?: Record<string, Record<string, boolean>>
): Promise<TestSubmission> {
    try {
        logger.info('📤 Submitting test:', testId, sessionId);
        logger.info('   Total questions:', questions.length);

        // Build user_answers array - ITERATE OVER ALL QUESTIONS
        const userAnswers = questions.map(q => {
            const qid = q.question_id;
            const qtype = q.question_type || 'mcq'; // Default to mcq if type missing

            switch (qtype) {
                case 'mcq':
                case 'mcq_multiple':
                    return {
                        question_id: qid,
                        question_type: qtype,
                        selected_answer_keys: answers[qid] ? (Array.isArray(answers[qid]) ? answers[qid] : [answers[qid]]) : []
                    };

                case 'essay':
                    const essayData = essayAnswers?.[qid];
                    return {
                        question_id: qid,
                        question_type: 'essay',
                        essay_answer: essayData?.essay_answer || '',
                        media_attachments: essayData?.media_attachments || []
                    };

                case 'matching':
                    return {
                        question_id: qid,
                        question_type: 'matching',
                        matches: matchingAnswers?.[qid] || {} // Empty object if no matches
                    };

                case 'map_labeling':
                    return {
                        question_id: qid,
                        question_type: 'map_labeling',
                        labels: mapLabelingAnswers?.[qid] || {} // Empty object if no labels
                    };

                case 'completion':
                    return {
                        question_id: qid,
                        question_type: 'completion',
                        answers: completionAnswers?.[qid] || {} // Empty object if no answers
                    };

                case 'sentence_completion':
                    return {
                        question_id: qid,
                        question_type: 'sentence_completion',
                        answers: sentenceCompletionAnswers?.[qid] || {} // Empty object if no answers
                    };

                case 'short_answer':
                    return {
                        question_id: qid,
                        question_type: 'short_answer',
                        answers: shortAnswerAnswers?.[qid] || {} // Empty object if no answers
                    };

                case 'true_false_multiple':
                    return {
                        question_id: qid,
                        question_type: 'true_false_multiple',
                        user_answer: trueFalseAnswers?.[qid] || {} // Empty object if no answers
                    };

                default:
                    // Fallback to MCQ for unknown types
                    return {
                        question_id: qid,
                        question_type: 'mcq',
                        selected_answer_keys: []
                    };
            }
        });

        logger.info('📋 Built user_answers:', userAnswers.length, 'questions');
        userAnswers.forEach((ua, i) => {
            logger.info(`   ${i + 1}. ${ua.question_id} (${ua.question_type})`);
        });

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/submit`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                session_id: sessionId,
                user_answers: userAnswers,
            }),
        });

        const result = await handleResponse<TestSubmission>(response);
        logger.info('✅ Test submitted successfully. Score:', result.score);
        return result;
    } catch (error) {
        logger.error('❌ Failed to submit test:', error);
        throw error;
    }
}

/**
 * Resume incomplete test
 */
export async function resumeTest(testId: string): Promise<TestSession> {
    try {
        logger.info('🔄 Resuming test:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/resume`, {
            method: 'POST',
            headers,
        });

        const result = await handleResponse<TestSession>(response);
        logger.info('✅ Test resumed:', result.session_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to resume test:', error);
        throw error;
    }
}

// ==================== Progress & Results ====================

/**
 * Get test attempt information
 */
export async function getTestAttempts(testId: string): Promise<TestAttemptInfo> {
    try {
        logger.info('📊 Fetching test attempts:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/attempts`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<TestAttemptInfo>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch test attempts:', error);
        throw error;
    }
}

/**
 * Get test participants (OWNER ONLY)
 * @param testId - Test ID
 * @param page - Page number (default: 1)
 * @param pageSize - Items per page (default: 20)
 * @param sortBy - Sort order: 'latest' | 'highest_score' | 'lowest_score' | 'most_attempts'
 * @returns List of participants with statistics
 */
export async function getTestParticipants(
    testId: string,
    page: number = 1,
    pageSize: number = 20,
    sortBy: 'latest' | 'highest_score' | 'lowest_score' | 'most_attempts' = 'latest'
): Promise<GetTestParticipantsResponse> {
    try {
        logger.info('👥 Fetching test participants:', { testId, page, pageSize, sortBy });

        const headers = await getAuthHeaders();
        const queryParams = new URLSearchParams({
            page: page.toString(),
            page_size: pageSize.toString(),
            sort_by: sortBy,
        });

        const response = await fetch(
            `${API_BASE_URL}/api/v1/tests/${testId}/participants?${queryParams}`,
            {
                method: 'GET',
                headers,
            }
        );

        const result = await handleResponse<GetTestParticipantsResponse>(response);
        logger.info('✅ Participants fetched successfully:', result.participants.length);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch participants:', error);
        throw error;
    }
}

/**
 * Get test ratings (public)
 * @param testId - Test ID
 * @param page - Page number (default: 1)
 * @param pageSize - Items per page (default: 20, max: 100)
 * @param sortBy - Sort order: 'newest' | 'oldest' | 'highest' | 'lowest'
 * @returns List of ratings with user info and pagination
 */
export async function getTestRatings(
    testId: string,
    page: number = 1,
    pageSize: number = 20,
    sortBy: 'newest' | 'oldest' | 'highest' | 'lowest' = 'newest'
): Promise<GetTestRatingsResponse> {
    try {
        logger.info('⭐ Fetching test ratings:', { testId, page, pageSize, sortBy });

        const headers = await getOptionalAuthHeaders(); // Allow anonymous access
        const queryParams = new URLSearchParams({
            page: page.toString(),
            page_size: pageSize.toString(),
            sort_by: sortBy,
        });

        const response = await fetch(
            `${API_BASE_URL}/api/v1/marketplace/tests/${testId}/ratings?${queryParams}`,
            {
                method: 'GET',
                headers,
            }
        );

        const result = await handleResponse<GetTestRatingsResponse>(response);
        logger.info('✅ Ratings fetched successfully:', result.data.ratings.length);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch ratings:', error);
        throw error;
    }
}

/**
 * Submit rating for a test (PARTICIPANTS ONLY)
 * @param testId - Test ID
 * @param rating - Rating value (1-5 stars)
 * @param comment - Optional comment
 * @returns Success response with rating_id
 */
export async function submitTestRating(
    testId: string,
    rating: number,
    comment?: string
): Promise<SubmitRatingResponse> {
    try {
        logger.info('⭐ Submitting test rating:', { testId, rating, hasComment: !!comment });

        const headers = await getAuthHeaders();
        const body: SubmitRatingRequest = {
            rating,
            ...(comment && { comment }),
        };

        const response = await fetch(
            `${API_BASE_URL}/api/v1/marketplace/tests/${testId}/ratings`,
            {
                method: 'POST',
                headers,
                body: JSON.stringify(body),
            }
        );

        const result = await handleResponse<SubmitRatingResponse>(response);
        logger.info('✅ Rating submitted successfully');
        return result;
    } catch (error) {
        logger.error('❌ Failed to submit rating:', error);
        throw error;
    }
}

/**
 * Get my tests (created by me)
 * @param limit - Number of tests to return (default: 10, max: 100)
 * @param offset - Number of tests to skip (default: 0)
 * @returns Paginated list of tests with metadata
 */
export async function getMyTests(limit: number = 10, offset: number = 0): Promise<GetMyTestsResponse> {
    try {
        logger.info('📚 Fetching my tests', { limit, offset });

        const headers = await getAuthHeaders();
        const response = await fetch(
            `${API_BASE_URL}/api/v1/tests/me/tests?limit=${limit}&offset=${offset}`,
            {
                method: 'GET',
                headers,
            }
        );

        const result = await handleResponse<GetMyTestsResponse>(response);
        logger.info('✅ Fetched my tests:', {
            count: result.tests.length,
            total: result.total,
            has_more: result.has_more
        });
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch my tests:', error);
        throw error;
    }
}

/**
 * Get my submissions (grouped by test with submission history)
 * NEW: Updated November 29, 2025 to return grouped submissions
 */
export async function getMySubmissions(): Promise<GetMySubmissionsGroupedResponse> {
    try {
        logger.info('📝 Fetching my submissions (grouped)');

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/me/submissions`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<GetMySubmissionsGroupedResponse>(response);
        logger.info('✅ Grouped submissions loaded:', result.total_tests, 'tests');
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch my submissions:', error);
        throw error;
    }
}

/**
 * Get submission details
 */
export async function getSubmissionDetails(submissionId: string): Promise<TestSubmission> {
    try {
        logger.info('📄 Fetching submission details:', submissionId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/submissions/${submissionId}`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<TestSubmission>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch submission details:', error);
        throw error;
    }
}

/**
 * Get detailed submission results with answers and explanations
 */
export async function getSubmissionResults(submissionId: string): Promise<TestSubmissionDetail> {
    try {
        logger.info('📊 Fetching submission results:', submissionId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/me/submissions/${submissionId}`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<TestSubmissionDetail>(response);
        logger.info('✅ Submission results fetched:', {
            score: result.score,
            percentage: result.score_percentage,
            passed: result.is_passed,
        });
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch submission results:', error);
        throw error;
    }
}

// ==================== HTTP Fallback for Progress Saving ====================

/**
 * Save progress (HTTP fallback when WebSocket unavailable)
 */
export async function saveTestProgress(
    testId: string,
    sessionId: string,
    answers: Record<string, string>,
    timeRemainingSeconds: number
): Promise<{ success: boolean }> {
    try {
        logger.info('💾 Saving test progress (HTTP):', testId, sessionId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/progress/save`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                session_id: sessionId,
                answers,
                time_remaining_seconds: timeRemainingSeconds,
            }),
        });

        const result = await handleResponse<{ success: boolean }>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to save progress:', error);
        throw error;
    }
}

/**
 * Get progress (HTTP fallback)
 */
export async function getTestProgress(testId: string, sessionId: string): Promise<TestSession> {
    try {
        logger.info('📖 Fetching test progress:', testId, sessionId);

        const headers = await getAuthHeaders();
        const response = await fetch(
            `${API_BASE_URL}/api/v1/tests/${testId}/progress?session_id=${sessionId}`,
            {
                method: 'GET',
                headers,
            }
        );

        const result = await handleResponse<TestSession>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch progress:', error);
        throw error;
    }
}

/**
 * Get test status (for async generation polling)
 * NEW in V2
 */
export async function getTestStatus(testId: string): Promise<{
    test_id: string;
    status: 'pending' | 'generating' | 'ready' | 'failed' | 'draft';
    progress_percent?: number;
    message?: string;
    error_message?: string;
    num_questions?: number;
    title?: string;
}> {
    try {
        logger.info('🔍 Checking test status:', testId);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/status`, {
            method: 'GET',
            headers,
        });

        const result = await handleResponse<{
            test_id: string;
            status: 'pending' | 'generating' | 'ready' | 'failed' | 'draft';
            progress_percent?: number;
            message?: string;
            error_message?: string;
            num_questions?: number;
            title?: string;
        }>(response);
        return result;
    } catch (error) {
        logger.error('❌ Failed to fetch test status:', error);
        throw error;
    }
}

/**
 * Duplicate test with auto-increment title
 * NEW in V2
 */
export async function duplicateTest(
    testId: string,
    newTitle?: string
): Promise<Test> {
    try {
        logger.info('📋 Duplicating test:', testId, newTitle || '(auto title)');

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/duplicate`, {
            method: 'POST',
            headers,
            body: JSON.stringify(newTitle ? { new_title: newTitle } : {}),
        });

        const result = await handleResponse<Test>(response);
        logger.info('✅ Test duplicated successfully:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to duplicate test:', error);
        throw error;
    }
}

/**
 * Translate test to another language using AI
 * NEW: December 3, 2025 - Gemini 2.0 Flash Exp translation
 */
export async function translateTest(
    testId: string,
    targetLanguage: string,
    newTitle?: string
): Promise<{
    success: boolean;
    test_id: string;
    status: string;
    original_test_id: string;
    target_language: string;
    message: string;
    created_at: string;
}> {
    try {
        logger.info('🌍 Translating test:', { testId, targetLanguage, newTitle });

        const headers = await getAuthHeaders();
        const body: { target_language: string; new_title?: string } = {
            target_language: targetLanguage
        };
        if (newTitle) {
            body.new_title = newTitle;
        }

        const response = await fetch(`${API_BASE_URL}/api/v1/tests/${testId}/translate`, {
            method: 'POST',
            headers,
            body: JSON.stringify(body),
        });

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            status: string;
            original_test_id: string;
            target_language: string;
            message: string;
            created_at: string;
        }>(response);

        logger.info('✅ Translation started:', result.test_id, 'Status:', result.status);
        return result;
    } catch (error) {
        logger.error('❌ Failed to translate test:', error);
        throw error;
    }
}

/**
 * Create manual test (no AI generation)
 * NEW in V2
 */
export async function createManualTest(config: {
    title: string;
    description?: string;
    creator_name?: string; // NEW: Optional creator display name
    language?: 'vi' | 'en'; // NEW: Test language (17 languages supported by backend)
    time_limit_minutes: number;
    max_retries?: number;
    deadline?: string;
    questions?: TestQuestion[];
    is_active?: boolean;
    is_draft?: boolean;
    attachments?: Omit<TestAttachment, 'attachment_id' | 'uploaded_at'>[]; // NEW: Optional attachments
}): Promise<Test> {
    try {
        logger.info('✍️ Creating manual test:', config.title);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/manual`, {
            method: 'POST',
            headers,
            body: JSON.stringify(config),
        });

        const result = await handleResponse<Test>(response);
        logger.info('✅ Manual test created:', result.test_id, 'Status:', result.status);
        return result;
    } catch (error) {
        logger.error('❌ Failed to create manual test:', error);
        throw error;
    }
}

/**
 * Preview questions from multiple tests before merging
 * POST /api/v1/tests/preview-questions
 * Dec 11, 2025 - Test Merge Feature
 */
export interface PreviewQuestionsResponse {
    success: boolean;
    tests: Record<string, {
        test_id: string;
        title: string;
        test_type: string;
        num_questions: number;
        questions: Array<{
            index: number;
            question_type: string;
            question_text: string;
            has_media: boolean;
            instruction?: string;
            num_options?: number;
            num_correct_answers?: number;
            max_score?: number;
            left_items_count?: number;
            right_options_count?: number;
            num_blanks?: number;
            max_words?: number;
        }>;
    }>;
    total_tests: number;
}

export async function previewQuestions(testIds: string[]): Promise<PreviewQuestionsResponse> {
    try {
        logger.info('👀 Previewing questions from tests:', testIds);

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/preview-questions`, {
            method: 'POST',
            headers,
            body: JSON.stringify({ test_ids: testIds }),
        });

        const result = await handleResponse<PreviewQuestionsResponse>(response);
        logger.info('✅ Questions preview fetched:', result.total_tests, 'tests');
        return result;
    } catch (error) {
        logger.error('❌ Failed to preview questions:', error);
        throw error;
    }
}

/**
 * Merge multiple tests into one new test
 * POST /api/v1/tests/merge
 * Dec 11, 2025 - Test Merge Feature
 */
export interface MergeTestsRequest {
    source_test_ids: string[]; // 2-10 test IDs
    title: string; // 5-200 chars
    description?: string; // max 1000 chars
    creator_name?: string; // 2-100 chars
    test_type: 'mcq' | 'essay' | 'mixed' | 'listening' | 'auto';
    test_category?: 'academic' | 'diagnostic'; // default: academic
    time_limit_minutes: number; // 1-300, default: 30
    max_retries?: number; // 1-10, default: 3
    passing_score?: number; // 0-100, default: 50
    mcq_points?: number; // for mixed type
    essay_points?: number; // for mixed type
    essay_grading_criteria?: string; // max 2000 chars
    question_selection: 'all' | 'random' | 'custom'; // default: all
    max_questions?: number; // required if question_selection=random
    custom_selection?: Record<string, {
        question_indices: number[];
        part_title?: string;
        part_description?: string;
    }>; // required if question_selection=custom
    deadline?: string; // ISO datetime
    show_answers_timing?: 'immediate' | 'after_deadline'; // default: immediate
}

export interface MergeTestsResponse {
    success: boolean;
    test_id: string;
    title: string;
    test_type: string;
    num_questions: number;
    num_mcq_questions: number;
    num_essay_questions: number;
    max_points: number;
    source_tests: number;
    created_at: string;
    message: string;
    parts?: Array<{
        part_number: number;
        part_title?: string;
        part_description?: string;
        source_test_id: string;
        source_test_title: string;
        question_start_index: number;
        question_end_index: number;
        num_questions: number;
    }>;
}

export async function mergeTests(request: MergeTestsRequest): Promise<MergeTestsResponse> {
    try {
        logger.info('🔗 Merging tests:', request.source_test_ids.length, 'tests');

        const headers = await getAuthHeaders();
        const response = await fetch(`${API_BASE_URL}/api/v1/tests/merge`, {
            method: 'POST',
            headers,
            body: JSON.stringify(request),
        });

        const result = await handleResponse<MergeTestsResponse>(response);
        logger.info('✅ Tests merged successfully:', result.test_id);
        return result;
    } catch (error) {
        logger.error('❌ Failed to merge tests:', error);
        throw error;
    }
}

// Export service object for easy import
export const onlineTestService = {
    // Generation
    generateTestFromDocument,
    generateTestFromAI,
    generateListeningTest, // NEW: Dec 8, 2025 - Listening test generation

    // NEW in V2
    getTestStatus,
    duplicateTest,
    translateTest, // NEW: December 3, 2025 - AI translation
    createManualTest,

    // Test Merge (Dec 11, 2025)
    previewQuestions,
    mergeTests,

    // CRUD
    getTest,
    getTestPreview,
    getPublicTestDetails,
    getPublicTestDetailsBySlug, // NEW: Fetch by slug for SEO
    updateTestQuestions,
    updateTestConfig,
    updateMarketplaceConfig,
    deleteTest,

    // Attachments (November 14, 2025)
    getPresignedUrl,
    uploadToR2,
    getAttachments,
    addAttachment,
    updateAttachment,
    deleteAttachment,

    // Media Management (November 12, 2025)
    uploadQuestionMedia: async (
        testId: string,
        questionId: string,
        file: File,
        mediaType: 'image' | 'audio',
        description?: string
    ): Promise<{
        success: boolean;
        test_id: string;
        question_id: string;
        media_type: string;
        media_url: string;
        media_description?: string;
        file_size_mb: number;
    }> => {
        const formData = new FormData();
        formData.append('media_file', file);
        formData.append('media_type', mediaType);
        if (description) {
            formData.append('description', description);
        }

        logger.info('📤 Uploading question media:', { testId, questionId, mediaType, fileName: file.name });

        const { firebaseTokenManager } = await import('./firebaseTokenManager');
        const token = await firebaseTokenManager.getValidToken();

        const headers: HeadersInit = {};
        if (token) {
            headers['Authorization'] = `Bearer ${token}`;
        }

        const response = await fetch(
            `${API_BASE_URL}/api/v1/tests/${testId}/questions/${questionId}/media`,
            {
                method: 'POST',
                headers,
                body: formData,
            }
        );

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            question_id: string;
            media_type: string;
            media_url: string;
            media_description?: string;
            file_size_mb: number;
        }>(response);

        logger.info('✅ Media uploaded successfully:', result);
        return result;
    },

    deleteQuestionMedia: async (testId: string, questionId: string): Promise<{
        success: boolean;
        test_id: string;
        question_id: string;
        deleted_media_url: string;
    }> => {
        logger.info('🗑️ Deleting question media:', { testId, questionId });

        const headers = await getAuthHeaders();
        const response = await fetch(
            `${API_BASE_URL}/api/v1/tests/${testId}/questions/${questionId}/media`,
            {
                method: 'DELETE',
                headers,
            }
        );

        const result = await handleResponse<{
            success: boolean;
            test_id: string;
            question_id: string;
            deleted_media_url: string;
        }>(response);

        logger.info('✅ Media deleted successfully:', result);
        return result;
    },

    // Taking
    startTest,
    getPresignedUrlForAnswerMedia,
    submitTest,
    resumeTest,

    // Progress & Results
    getTestAttempts,
    getMyTests,
    getMySubmissions,
    getSubmissionDetails,
    getSubmissionResults,

    // HTTP Fallback
    saveTestProgress,
    getTestProgress,

    // Essay Grading (November 28, 2025 - Phases 4-5)
    getGradingQueue: async (
        testId: string,
        status?: 'pending' | 'in_progress' | 'completed'
    ): Promise<GetGradingQueueResponse> => {
        try {
            logger.info('📋 Fetching grading queue:', testId, status);

            const headers = await getAuthHeaders();
            const url = new URL(`${API_BASE_URL}/api/v1/tests/${testId}/grading-queue`);
            if (status) {
                url.searchParams.append('status', status);
            }

            const response = await fetch(url.toString(), { headers });
            const result = await handleResponse<GetGradingQueueResponse>(response);

            logger.info('✅ Grading queue fetched:', result.total_count, 'submissions');
            return result;
        } catch (error) {
            logger.error('❌ Failed to fetch grading queue:', error);
            throw error;
        }
    },

    getGradingView: async (submissionId: string): Promise<GetGradingViewResponse> => {
        try {
            logger.info('📖 Fetching grading view:', submissionId);

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/grading-view`,
                { headers }
            );

            const result = await handleResponse<GetGradingViewResponse>(response);
            logger.info('✅ Grading view fetched:', result.essay_questions.length, 'essay questions');
            return result;
        } catch (error) {
            logger.error('❌ Failed to fetch grading view:', error);
            throw error;
        }
    },

    // NEW: Get submission grading details (includes sample answers)
    getGradingDetails: async (submissionId: string): Promise<GetGradingDetailsResponse> => {
        try {
            logger.info('📖 Fetching grading details:', submissionId);

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/grading-details`,
                { headers }
            );

            const result = await handleResponse<GetGradingDetailsResponse>(response);
            logger.info('✅ Grading details fetched:', result.essay_questions.length, 'essay questions');
            return result;
        } catch (error) {
            logger.error('❌ Failed to fetch grading details:', error);
            throw error;
        }
    },

    // Get AI evaluation history for submission
    getSubmissionEvaluations: async (
        submissionId: string,
        page: number = 1,
        limit: number = 10
    ): Promise<GetSubmissionEvaluationsResponse> => {
        try {
            logger.info('🤖 Fetching AI evaluation history:', submissionId);

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/evaluations?page=${page}&limit=${limit}`,
                { headers }
            );

            const result = await handleResponse<GetSubmissionEvaluationsResponse>(response);
            logger.info('✅ AI evaluation history fetched:', result.evaluations.length, 'evaluations');
            return result;
        } catch (error) {
            logger.error('❌ Failed to fetch AI evaluation history:', error);
            throw error;
        }
    },

    gradeEssay: async (
        submissionId: string,
        request: GradeEssayRequest
    ): Promise<GradeEssayResponse> => {
        try {
            logger.info('✍️ Grading essay:', submissionId, request.question_id);

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/grade-essay`,
                {
                    method: 'POST',
                    headers,
                    body: JSON.stringify(request),
                }
            );

            const result = await handleResponse<GradeEssayResponse>(response);
            logger.info('✅ Essay graded successfully:', result.grading_status);
            return result;
        } catch (error) {
            logger.error('❌ Failed to grade essay:', error);
            throw error;
        }
    },

    gradeAllEssays: async (
        submissionId: string,
        request: GradeAllEssaysRequest
    ): Promise<GradeAllEssaysResponse> => {
        try {
            logger.info('✍️ Grading all essays:', submissionId, request.grades.length, 'questions');

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/grade-all-essays`,
                {
                    method: 'POST',
                    headers,
                    body: JSON.stringify(request),
                }
            );

            const result = await handleResponse<GradeAllEssaysResponse>(response);
            logger.info('✅ All essays graded successfully:', result.final_score);
            return result;
        } catch (error) {
            logger.error('❌ Failed to grade all essays:', error);
            throw error;
        }
    },

    updateEssayGrade: async (
        submissionId: string,
        request: GradeEssayRequest
    ): Promise<GradeEssayResponse> => {
        try {
            logger.info('📝 Updating essay grade:', submissionId, request.question_id);

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/submissions/${submissionId}/update-essay-grade`,
                {
                    method: 'PATCH',
                    headers,
                    body: JSON.stringify(request),
                }
            );

            const result = await handleResponse<GradeEssayResponse>(response);
            logger.info('✅ Essay grade updated successfully');
            return result;
        } catch (error) {
            logger.error('❌ Failed to update essay grade:', error);
            throw error;
        }
    },

    getGradingDashboard: async (): Promise<GetGradingDashboardResponse> => {
        try {
            logger.info('📊 Fetching grading dashboard');

            const headers = await getAuthHeaders();
            const response = await fetch(
                `${API_BASE_URL}/api/v1/tests/me/grading-dashboard`,
                { headers }
            );

            const result = await handleResponse<GetGradingDashboardResponse>(response);
            logger.info('✅ Grading dashboard fetched:', result.total_pending, 'pending');
            return result;
        } catch (error) {
            logger.error('❌ Failed to fetch grading dashboard:', error);
            throw error;
        }
    },
};
